### PR TITLE
feat(docs): types support & readme update

### PR DESCRIPTION
**Pull request by federico-bubble**

### CODE REVIEW

**Comment by city0666** [comment]
its crashing app

**Comment by federico-bubble** [comment]
@city0666 I'm sure you can provide some more insights, how are the types crashing the app?

**Comment by city0666** [comment]
we install yarn add yoti....
then pod install
after run-ios
then open app crashing 


thats situation, i already show to ur one of staff josh via teams you need more details i
create video and share you

**Comment by federico-bubble** [comment]
@city0666 Just made changes, can you please pull and try again

**Comment by city0666** [comment]
still have same issue


crashing 


Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 83FB6E0C-B57A-4968-8DDC-D1BDDAA7B451
CrashReporter Key:   71819046-14BB-2550-9DBD-01EB133374E9
Hardware Model:      MacBookPro18,2
Process:             yotiTesting [5263]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/B96AADF8-36DF-4931-B18F-864965A49564/data/Containers/Bundle/Application/1BB60A26-EE7E-457D-8261-245FA42221D1/yotiTesting.app/yotiTesting
Identifier:          org.reactjs.native.example.yotiTesting
Version:             1.0 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [1421]
Coalition:           com.apple.CoreSimulator.SimDevice.B96AADF8-36DF-4931-B18F-864965A49564 [928]
Responsible Process: SimulatorTrampoline [1375]

Date/Time:           2022-12-29 12:57:20.5727 +0530
Launch Time:         2022-12-29 12:57:20.4966 +0530
OS Version:          macOS 13.0.1 (22A400)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/SwiftProtobuf.framework/SwiftProtobuf
Referenced from: <F5B5E84F-AE4C-3C00-A2CE-20BB270BA025> /Users/USER/Library/Developer/CoreSimulator/Devices/B96AADF8-36DF-4931-B18F-864965A49564/data/Containers/Bundle/Application/1BB60A26-EE7E-457D-8261-245FA42221D1/yotiTesting.app/Frameworks/YotiSDKDocument.framework/YotiSDKDocument
Reason: tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/SwiftProtobuf.framework/SwiftProtobuf' (errno=2), '/usr/lib/swift/SwiftProtobuf.framework/SwiftProtobuf' (errno=2, not in dyld cache), '/Users/ammachi/Library/Developer/CoreSimulator/Devices/B96AADF8-36DF-4931-B18F-864965A49564/data/Containers/Bundle/Application/1BB60A26-EE7E-457D-8261-245FA42221D1/yotiTesting.app/Frameworks/YotiSDKDocument.framework/Frameworks/SwiftProtobuf.framework/SwiftProtobuf' (errno=2), '/Users/ammachi/Library/Developer/CoreSimulator/Device
(terminated at launch; ignore backtrace)

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	       0x107084e58 __abort_with_payload + 8
1   dyld                          	       0x10708f6c0 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10708f6f4 abort_with_payload + 16
3   dyld_sim                      	       0x106f2bcfc abort_with_payload + 40
4   dyld_sim                      	       0x106eebf38 dyld4::halt(char const*) + 324
5   dyld_sim                      	       0x106ee9c60 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3148
6   dyld_sim                      	       0x106ee9e78 _dyld_sim_prepare + 424
7   dyld                          	       0x10701b8bc dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 1264
8   dyld                          	       0x10701a13c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 272
9   dyld                          	       0x107019dc4 start + 2404


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016bdcf810   x3: 0x000000000000012a
    x4: 0x000000016bdcf410   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000011  x10: 0x0000000000000000  x11: 0x207972617262694c
   x12: 0x000000000000002f  x13: 0x0000000000000035  x14: 0x0000000000000002  x15: 0xffffffffffffffff
   x16: 0x0000000000000209  x17: 0x0000000107017e7c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016bdcf410  x21: 0x000000000000012a  x22: 0x000000016bdcf810  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016bdd0f30  x26: 0x000000016bdd0e48  x27: 0x0000000106f3c090
   x28: 0x0000000000000000   fp: 0x000000016bdcf3d0   lr: 0x000000010708f6c0
    sp: 0x000000016bdcf390   pc: 0x0000000107084e58 cpsr: 0x00001000
   far: 0x0000000106e00000  esr: 0x56000080  Address size fault

Binary Images:
       0x107014000 -        0x10709ffff dyld (*) <de46dd52-4994-3fd8-b4b4-e352a1a19354> /usr/lib/dyld
       0x106ee8000 -        0x106f37fff dyld_sim (*) <1772df31-9df3-36cc-a3c6-b34fd26bffe5> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"yotiTesting","timestamp":"2022-12-29 12:57:22.00 +0530","app_version":"1.0","slice_uuid":"40bc2198-e1f1-3dfb-a3e1-5c44823b0baf","build_version":"1","platform":7,"bundleID":"org.reactjs.native.example.yotiTesting","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0.1 (22A400)","roots_installed":0,"name":"yotiTesting","incident_id":"83FB6E0C-B57A-4968-8DDC-D1BDDAA7B451"}
{
  "uptime" : 260,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "coalitionID" : 928,
  "osVersion" : {
    "train" : "macOS 13.0.1",
    "build" : "22A400",
    "releaseType" : "User"
  },
  "captureTime" : "2022-12-29 12:57:20.5727 +0530",
  "incident" : "83FB6E0C-B57A-4968-8DDC-D1BDDAA7B451",
  "pid" : 5263,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-12-29 12:57:20.4966 +0530",
  "procStartAbsTime" : 6467347209,
  "procExitAbsTime" : 6469133830,
  "procName" : "yotiTesting",
  "procPath" : "\/Users\/USER\/Library\/Developer\/CoreSimulator\/Devices\/B96AADF8-36DF-4931-B18F-864965A49564\/data\/Containers\/Bundle\/Application\/1BB60A26-EE7E-457D-8261-245FA42221D1\/yotiTesting.app\/yotiTesting",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1","CFBundleIdentifier":"org.reactjs.native.example.yotiTesting"},
  "storeInfo" : {"deviceIdentifierForVendor":"A0CE1BD3-1119-5103-8C73-CB6D21C216D6","thirdParty":true},
  "parentProc" : "launchd_sim",
  "parentPid" : 1421,
  "coalitionName" : "com.apple.CoreSimulator.SimDevice.B96AADF8-36DF-4931-B18F-864965A49564",
  "crashReporterKey" : "71819046-14BB-2550-9DBD-01EB133374E9",
  "responsiblePid" : 1375,
  "responsibleProc" : "SimulatorTrampoline",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/SwiftProtobuf.framework\/SwiftProtobuf","Referenced from: <F5B5E84F-AE4C-3C00-A2CE-20BB270BA025> \/Users\/USER\/Library\/Developer\/CoreSimulator\/Devices\/B96AADF8-36DF-4931-B18F-864965A49564\/data\/Containers\/Bundle\/Application\/1BB60A26-EE7E-457D-8261-245FA42221D1\/yotiTesting.app\/Frameworks\/YotiSDKDocument.framework\/YotiSDKDocument","Reason: tried: '\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot\/usr\/lib\/swift\/SwiftProtobuf.framework\/SwiftProtobuf' (errno=2), '\/usr\/lib\/swift\/SwiftProtobuf.framework\/SwiftProtobuf' (errno=2, not in dyld cache), '\/Users\/ammachi\/Library\/Developer\/CoreSimulator\/Devices\/B96AADF8-36DF-4931-B18F-864965A49564\/data\/Containers\/Bundle\/Application\/1BB60A26-EE7E-457D-8261-245FA42221D1\/yotiTesting.app\/Frameworks\/YotiSDKDocument.framework\/Frameworks\/SwiftProtobuf.framework\/SwiftProtobuf' (errno=2), '\/Users\/ammachi\/Library\/Developer\/CoreSimulator\/Device"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":24115,"threadState":{"x":[{"value":6},{"value":1},{"value":6104610832},{"value":298},{"value":6104609808},{"value":0},{"value":0},{"value":0},{"value":32},{"value":17},{"value":0},{"value":2340027244252129612},{"value":47},{"value":53},{"value":2},{"value":18446744073709551615},{"value":521},{"value":4412505724,"symbolLocation":56,"symbol":"fcntl"},{"value":0},{"value":0},{"value":6104609808},{"value":298},{"value":6104610832},{"value":1},{"value":6},{"value":6104616752},{"value":6104616520},{"value":4411605136,"symbolLocation":0,"symbol":"_NSConcreteStackBlock"},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4412995264},"cpsr":{"value":4096},"fp":{"value":6104609744},"sp":{"value":6104609680},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4412952152,"matchesCrashFrame":1},"far":{"value":4410310656}},"frames":[{"imageOffset":462424,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":505536,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":505588,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":277756,"symbol":"abort_with_payload","symbolLocation":40,"imageIndex":1},{"imageOffset":16184,"symbol":"dyld4::halt(char const*)","symbolLocation":324,"imageIndex":1},{"imageOffset":7264,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3148,"imageIndex":1},{"imageOffset":7800,"symbol":"_dyld_sim_prepare","symbolLocation":424,"imageIndex":1},{"imageOffset":30908,"symbol":"dyld4::prepareSim(dyld4::RuntimeState&, char const*)","symbolLocation":1264,"imageIndex":0},{"imageOffset":24892,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":272,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4412489728,
    "size" : 573440,
    "uuid" : "de46dd52-4994-3fd8-b4b4-e352a1a19354",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4411260928,
    "size" : 327680,
    "uuid" : "1772df31-9df3-36cc-a3c6-b34fd26bffe5",
    "path" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime\/Contents\/Resources\/RuntimeRoot\/usr\/lib\/dyld_sim",
    "name" : "dyld_sim"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=800.6M resident=0K(0%) swapped_out_or_unallocated=800.6M(100%)\nWritable regions: Total=10.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         32K        2 \n__DATA                            10.4M      416 \n__DATA_CONST                      37.5M      411 \n__DATA_DIRTY                        66K       11 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       408.2M       34 \n__LLVM                            46.2M        3 \n__LLVM_COV                         288K       11 \n__OBJC_RO                         28.3M        1 \n__OBJC_RW                          880K        1 \n__TEXT                           392.4M      420 \ndyld private memory                768K        3 \n===========                     =======  ======= \nTOTAL                            989.0M     1316 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62cdf63ddb3b7109d6d765cc",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_TMDC" : "62cdf6dddb3b7109d6d765cd"
      },
      "deploymentId" : 240000007
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {
        "PROACTIVE_MAIL_INTELLIGENCE_SALIENCY" : "636525247ea6e25a76dc2008"
      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro18,2, BootROM 8419.41.10, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

**Comment by city0666** [comment]
#import "ZoomPublicApi.h" 'ZoomPublicApi.h' file not found
i check xcode got error missing file

**Comment by federico-bubble** [comment]
So, the one issue you are facing is the same issue I faced when first installing the library:
`Library not loaded: @rpath/SwiftProtobuf.framework/SwiftProtobuf`.

After long struggling with this issue I found that it is triggered when the flag `use_frameworks!` is not set in your `podfile`. I added it in the README here: https://github.com/getyoti/yoti-doc-scan-react-native/pull/25/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23-R24

Regardless, I believe this error is coming from the latest version of master, not from the changes in this PR. It'd be very useful if you can test pulling from the latest version of master and try again.

**Comment by city0666** [comment]
hi

this link dnt have content  https://github.com/getyoti/yoti-doc-scan-react-native/pull/25/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23-R24 https://github.com/getyoti/yoti-doc-scan-react-native/pull/25/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23-R24

**Review by city0666 — COMMENTED** [review]
hi

**Pull request closed without merging**
